emptyCreds = { 'foo' : 'bar' }

urlList = {
    'GOOGLE':{'appname':'Google', 'customer':'Google search', 'url':'https://www.google.com', 'credentials':emptyCreds, 'payload':'EMPTY', 'failure_history':[0,0,0,0,0,0], 'rt_history':[0,0,0,0,0,0], 'orange_since':'-', 'red_since':'-', 'orange_sent':0, 'red_sent':0, 'release_def_ids':[0], 'latest_deployment':'None', 'protocol':'HTTPS', 'retries':3, 'timeout':10, 'http_success':[200,301,302], 'http_failure':[400,401,404,500], 'http_maintenance':[307,503], 'payload_success':'Feeling Lucky', 'payload_maintenance':'maintenance', 'payload_failure':'error', 'flappingCntr':0, 'flappingStatus':0, 'previousStatus':'None', 'currentStatus':'None', 'ack':'19700101', 'runbook':''},
    'FB':{'appname':'Facebook', 'customer':'Social network', 'url':'https://www.facebook.com', 'credentials':emptyCreds, 'payload':'EMPTY', 'failure_history':[0,0,0,0,0,0], 'rt_history':[0,0,0,0,0,0], 'orange_since':'-', 'red_since':'-', 'orange_sent':0, 'red_sent':0, 'release_def_ids':[0], 'latest_deployment':'None', 'protocol':'HTTPS', 'retries':3, 'timeout':10, 'http_success':[200,301,302], 'http_failure':[400,401,404,500], 'http_maintenance':[307,503], 'payload_success':'Create a Page for a celebrity, band or business.', 'payload_maintenance':'maintenance', 'payload_failure':'error', 'flappingCntr':0, 'flappingStatus':0, 'previousStatus':'None', 'currentStatus':'None', 'ack':'19700101', 'runbook':''},
    'APPLE':{'appname':'Apple', 'customer':'Computers', 'url':'https://www.apple.com', 'credentials':emptyCreds, 'payload':'EMPTY', 'failure_history':[0,0,0,0,0,0], 'rt_history':[0,0,0,0,0,0], 'orange_since':'-', 'red_since':'-', 'orange_sent':0, 'red_sent':0, 'release_def_ids':[0], 'latest_deployment':'None', 'protocol':'HTTPS', 'retries':3, 'timeout':10, 'http_success':[200,301,302], 'http_failure':[400,401,404,500], 'http_maintenance':[307,503], 'payload_success':'shop online', 'payload_maintenance':'maintenance', 'payload_failure':'error', 'flappingCntr':0, 'flappingStatus':0, 'previousStatus':'None', 'currentStatus':'None', 'ack':'19700101', 'runbook':''},
    'ROLAND':{'appname':'Roland Radio', 'customer':'Amstrad CPC music', 'url':'https://rolandradio.net', 'credentials':emptyCreds, 'payload':'EMPTY', 'failure_history':[0,0,0,0,0,0], 'rt_history':[0,0,0,0,0,0], 'orange_since':'-', 'red_since':'-', 'orange_sent':0, 'red_sent':0, 'release_def_ids':[0], 'latest_deployment':'None', 'protocol':'HTTPS', 'retries':3, 'timeout':10, 'http_success':[200,301,302], 'http_failure':[400,401,404,500], 'http_maintenance':[307,503], 'payload_success':'Welcome to your Amstrad CPC Chiptune Radio', 'payload_maintenance':'maintenance', 'payload_failure':'error', 'flappingCntr':0, 'flappingStatus':0, 'previousStatus':'None', 'currentStatus':'None', 'ack':'19700101', 'runbook':''},
    'TRELLO':{'appname':'Trello', 'customer':'Kanban', 'url':'https://trello.com', 'credentials':emptyCreds, 'payload':'EMPTY', 'failure_history':[0,0,0,0,0,0], 'rt_history':[0,0,0,0,0,0], 'orange_since':'-', 'red_since':'-', 'orange_sent':0, 'red_sent':0, 'release_def_ids':[0], 'latest_deployment':'None', 'protocol':'HTTPS', 'retries':3, 'timeout':10, 'http_success':[200,301,302], 'http_failure':[400,401,404,500], 'http_maintenance':[307,503], 'payload_success':'Trello helps teams work', 'payload_maintenance':'maintenance', 'payload_failure':'error', 'flappingCntr':0, 'flappingStatus':0, 'previousStatus':'None', 'currentStatus':'None', 'ack':'19700101', 'runbook':''}
}

ntAPICountriesList = {}

